version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
  web:
    build: .
    container_name: ollama_web
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - ollama
    ports:
      - "5000:5000"
volumes:
  ollama:
